describe('Checkout Test', () => {
  it('Complete Checkout', () => {
    cy.visit('https://www.saucedemo.com/')
    cy.get('#user-name').type('standard_user')
    cy.get('#password').type('secret_sauce')
    cy.get('#login-button').click()
    cy.get('#add-to-cart-sauce-labs-backpack').click()
    cy.get('a.shopping_cart_link').click()
    cy.get('#checkout').click()
    cy.get('#first-name').type('LL')
    cy.get('#last-name').type('LL')
    cy.get('#postal-code').type('606')
    cy.get('#continue').click()
    cy.get('#finish').click()
    cy.get('h2.complete-header').should('contain', 'Thank you for your order!')
  })
})